//
// AuthenticateUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthenticateUser: Codable, JSONEncodable, Hashable {

    public var pw: String?
    public var password: String?

    public init(pw: String? = nil, password: String? = nil) {
        self.pw = pw
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pw = "Pw"
        case password = "Password"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pw, forKey: .pw)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

