//
// DevicesDeviceInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DevicesDeviceInfo: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var id: String?
    public var lastUserName: String?
    public var appName: String?
    public var appVersion: String?
    public var lastUserId: String?
    public var dateLastActivity: Date?
    public var iconUrl: String?

    public init(name: String? = nil, id: String? = nil, lastUserName: String? = nil, appName: String? = nil, appVersion: String? = nil, lastUserId: String? = nil, dateLastActivity: Date? = nil, iconUrl: String? = nil) {
        self.name = name
        self.id = id
        self.lastUserName = lastUserName
        self.appName = appName
        self.appVersion = appVersion
        self.lastUserId = lastUserId
        self.dateLastActivity = dateLastActivity
        self.iconUrl = iconUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case id = "Id"
        case lastUserName = "LastUserName"
        case appName = "AppName"
        case appVersion = "AppVersion"
        case lastUserId = "LastUserId"
        case dateLastActivity = "DateLastActivity"
        case iconUrl = "IconUrl"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(lastUserName, forKey: .lastUserName)
        try container.encodeIfPresent(appName, forKey: .appName)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(lastUserId, forKey: .lastUserId)
        try container.encodeIfPresent(dateLastActivity, forKey: .dateLastActivity)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
    }
}

