//
// DlnaDeviceProfileInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DlnaDeviceProfileInfo: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case system = "System"
        case user = "User"
    }
    public var id: String?
    public var name: String?
    public var type: ModelType?

    public init(id: String? = nil, name: String? = nil, type: ModelType? = nil) {
        self.id = id
        self.name = name
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case type = "Type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

