//
// DlnaTranscodingProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DlnaTranscodingProfile: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case audio = "Audio"
        case video = "Video"
        case photo = "Photo"
    }
    public enum TranscodeSeekInfo: String, Codable, CaseIterable {
        case auto = "Auto"
        case bytes = "Bytes"
    }
    public enum Context: String, Codable, CaseIterable {
        case streaming = "Streaming"
        case _static = "Static"
    }
    public var container: String?
    public var type: ModelType?
    public var videoCodec: String?
    public var audioCodec: String?
    public var _protocol: String?
    public var estimateContentLength: Bool?
    public var enableMpegtsM2TsMode: Bool?
    public var transcodeSeekInfo: TranscodeSeekInfo?
    public var copyTimestamps: Bool?
    public var context: Context?
    public var maxAudioChannels: String?
    public var minSegments: Int?
    public var segmentLength: Int?
    public var breakOnNonKeyFrames: Bool?
    public var manifestSubtitles: String?

    public init(container: String? = nil, type: ModelType? = nil, videoCodec: String? = nil, audioCodec: String? = nil, _protocol: String? = nil, estimateContentLength: Bool? = nil, enableMpegtsM2TsMode: Bool? = nil, transcodeSeekInfo: TranscodeSeekInfo? = nil, copyTimestamps: Bool? = nil, context: Context? = nil, maxAudioChannels: String? = nil, minSegments: Int? = nil, segmentLength: Int? = nil, breakOnNonKeyFrames: Bool? = nil, manifestSubtitles: String? = nil) {
        self.container = container
        self.type = type
        self.videoCodec = videoCodec
        self.audioCodec = audioCodec
        self._protocol = _protocol
        self.estimateContentLength = estimateContentLength
        self.enableMpegtsM2TsMode = enableMpegtsM2TsMode
        self.transcodeSeekInfo = transcodeSeekInfo
        self.copyTimestamps = copyTimestamps
        self.context = context
        self.maxAudioChannels = maxAudioChannels
        self.minSegments = minSegments
        self.segmentLength = segmentLength
        self.breakOnNonKeyFrames = breakOnNonKeyFrames
        self.manifestSubtitles = manifestSubtitles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
        case type = "Type"
        case videoCodec = "VideoCodec"
        case audioCodec = "AudioCodec"
        case _protocol = "Protocol"
        case estimateContentLength = "EstimateContentLength"
        case enableMpegtsM2TsMode = "EnableMpegtsM2TsMode"
        case transcodeSeekInfo = "TranscodeSeekInfo"
        case copyTimestamps = "CopyTimestamps"
        case context = "Context"
        case maxAudioChannels = "MaxAudioChannels"
        case minSegments = "MinSegments"
        case segmentLength = "SegmentLength"
        case breakOnNonKeyFrames = "BreakOnNonKeyFrames"
        case manifestSubtitles = "ManifestSubtitles"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(container, forKey: .container)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(videoCodec, forKey: .videoCodec)
        try container.encodeIfPresent(audioCodec, forKey: .audioCodec)
        try container.encodeIfPresent(_protocol, forKey: ._protocol)
        try container.encodeIfPresent(estimateContentLength, forKey: .estimateContentLength)
        try container.encodeIfPresent(enableMpegtsM2TsMode, forKey: .enableMpegtsM2TsMode)
        try container.encodeIfPresent(transcodeSeekInfo, forKey: .transcodeSeekInfo)
        try container.encodeIfPresent(copyTimestamps, forKey: .copyTimestamps)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(maxAudioChannels, forKey: .maxAudioChannels)
        try container.encodeIfPresent(minSegments, forKey: .minSegments)
        try container.encodeIfPresent(segmentLength, forKey: .segmentLength)
        try container.encodeIfPresent(breakOnNonKeyFrames, forKey: .breakOnNonKeyFrames)
        try container.encodeIfPresent(manifestSubtitles, forKey: .manifestSubtitles)
    }
}

