//
// ForgotPassword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ForgotPassword: Codable, JSONEncodable, Hashable {

    public var enteredUsername: String?

    public init(enteredUsername: String? = nil) {
        self.enteredUsername = enteredUsername
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enteredUsername = "EnteredUsername"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enteredUsername, forKey: .enteredUsername)
    }
}

