//
// ForgotPasswordPin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ForgotPasswordPin: Codable, JSONEncodable, Hashable {

    public var pin: String?

    public init(pin: String? = nil) {
        self.pin = pin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pin = "Pin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pin, forKey: .pin)
    }
}

