//
// ImageByNameInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageByNameInfo: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var theme: String?
    public var context: String?
    public var fileLength: Int64?
    public var format: String?

    public init(name: String? = nil, theme: String? = nil, context: String? = nil, fileLength: Int64? = nil, format: String? = nil) {
        self.name = name
        self.theme = theme
        self.context = context
        self.fileLength = fileLength
        self.format = format
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case theme = "Theme"
        case context = "Context"
        case fileLength = "FileLength"
        case format = "Format"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(theme, forKey: .theme)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(fileLength, forKey: .fileLength)
        try container.encodeIfPresent(format, forKey: .format)
    }
}

