//
// IOFileSystemEntryInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IOFileSystemEntryInfo: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case file = "File"
        case directory = "Directory"
        case networkComputer = "NetworkComputer"
        case networkShare = "NetworkShare"
    }
    public var name: String?
    public var path: String?
    public var type: ModelType?

    public init(name: String? = nil, path: String? = nil, type: ModelType? = nil) {
        self.name = name
        self.path = path
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case path = "Path"
        case type = "Type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

