//
// LibraryMediaFolder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LibraryMediaFolder: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var id: String?
    public var subFolders: [LibrarySubFolder]?

    public init(name: String? = nil, id: String? = nil, subFolders: [LibrarySubFolder]? = nil) {
        self.name = name
        self.id = id
        self.subFolders = subFolders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case id = "Id"
        case subFolders = "SubFolders"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(subFolders, forKey: .subFolders)
    }
}

