//
// LibraryLibraryOptionInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LibraryLibraryOptionInfo: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var defaultEnabled: Bool?

    public init(name: String? = nil, defaultEnabled: Bool? = nil) {
        self.name = name
        self.defaultEnabled = defaultEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case defaultEnabled = "DefaultEnabled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(defaultEnabled, forKey: .defaultEnabled)
    }
}

