//
// LiveTvTimerInfoDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveTvTimerInfoDto: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case new = "New"
        case inProgress = "InProgress"
        case completed = "Completed"
        case cancelled = "Cancelled"
        case conflictedOk = "ConflictedOk"
        case conflictedNotOk = "ConflictedNotOk"
        case error = "Error"
    }
    public enum KeepUntil: String, Codable, CaseIterable {
        case untilDeleted = "UntilDeleted"
        case untilSpaceNeeded = "UntilSpaceNeeded"
        case untilWatched = "UntilWatched"
        case untilDate = "UntilDate"
    }
    public var status: Status?
    public var seriesTimerId: String?
    public var externalSeriesTimerId: String?
    public var runTimeTicks: Int64?
    public var programInfo: BaseItemDto?
    public var id: String?
    public var type: String?
    public var serverId: String?
    public var externalId: String?
    public var channelId: String?
    public var externalChannelId: String?
    public var channelName: String?
    public var channelPrimaryImageTag: String?
    public var programId: String?
    public var externalProgramId: String?
    public var name: String?
    public var overview: String?
    public var startDate: Date?
    public var endDate: Date?
    public var serviceName: String?
    public var priority: Int?
    public var prePaddingSeconds: Int?
    public var postPaddingSeconds: Int?
    public var isPrePaddingRequired: Bool?
    public var parentBackdropItemId: String?
    public var parentBackdropImageTags: [String]?
    public var isPostPaddingRequired: Bool?
    public var keepUntil: KeepUntil?

    public init(status: Status? = nil, seriesTimerId: String? = nil, externalSeriesTimerId: String? = nil, runTimeTicks: Int64? = nil, programInfo: BaseItemDto? = nil, id: String? = nil, type: String? = nil, serverId: String? = nil, externalId: String? = nil, channelId: String? = nil, externalChannelId: String? = nil, channelName: String? = nil, channelPrimaryImageTag: String? = nil, programId: String? = nil, externalProgramId: String? = nil, name: String? = nil, overview: String? = nil, startDate: Date? = nil, endDate: Date? = nil, serviceName: String? = nil, priority: Int? = nil, prePaddingSeconds: Int? = nil, postPaddingSeconds: Int? = nil, isPrePaddingRequired: Bool? = nil, parentBackdropItemId: String? = nil, parentBackdropImageTags: [String]? = nil, isPostPaddingRequired: Bool? = nil, keepUntil: KeepUntil? = nil) {
        self.status = status
        self.seriesTimerId = seriesTimerId
        self.externalSeriesTimerId = externalSeriesTimerId
        self.runTimeTicks = runTimeTicks
        self.programInfo = programInfo
        self.id = id
        self.type = type
        self.serverId = serverId
        self.externalId = externalId
        self.channelId = channelId
        self.externalChannelId = externalChannelId
        self.channelName = channelName
        self.channelPrimaryImageTag = channelPrimaryImageTag
        self.programId = programId
        self.externalProgramId = externalProgramId
        self.name = name
        self.overview = overview
        self.startDate = startDate
        self.endDate = endDate
        self.serviceName = serviceName
        self.priority = priority
        self.prePaddingSeconds = prePaddingSeconds
        self.postPaddingSeconds = postPaddingSeconds
        self.isPrePaddingRequired = isPrePaddingRequired
        self.parentBackdropItemId = parentBackdropItemId
        self.parentBackdropImageTags = parentBackdropImageTags
        self.isPostPaddingRequired = isPostPaddingRequired
        self.keepUntil = keepUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status = "Status"
        case seriesTimerId = "SeriesTimerId"
        case externalSeriesTimerId = "ExternalSeriesTimerId"
        case runTimeTicks = "RunTimeTicks"
        case programInfo = "ProgramInfo"
        case id = "Id"
        case type = "Type"
        case serverId = "ServerId"
        case externalId = "ExternalId"
        case channelId = "ChannelId"
        case externalChannelId = "ExternalChannelId"
        case channelName = "ChannelName"
        case channelPrimaryImageTag = "ChannelPrimaryImageTag"
        case programId = "ProgramId"
        case externalProgramId = "ExternalProgramId"
        case name = "Name"
        case overview = "Overview"
        case startDate = "StartDate"
        case endDate = "EndDate"
        case serviceName = "ServiceName"
        case priority = "Priority"
        case prePaddingSeconds = "PrePaddingSeconds"
        case postPaddingSeconds = "PostPaddingSeconds"
        case isPrePaddingRequired = "IsPrePaddingRequired"
        case parentBackdropItemId = "ParentBackdropItemId"
        case parentBackdropImageTags = "ParentBackdropImageTags"
        case isPostPaddingRequired = "IsPostPaddingRequired"
        case keepUntil = "KeepUntil"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(seriesTimerId, forKey: .seriesTimerId)
        try container.encodeIfPresent(externalSeriesTimerId, forKey: .externalSeriesTimerId)
        try container.encodeIfPresent(runTimeTicks, forKey: .runTimeTicks)
        try container.encodeIfPresent(programInfo, forKey: .programInfo)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(serverId, forKey: .serverId)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(channelId, forKey: .channelId)
        try container.encodeIfPresent(externalChannelId, forKey: .externalChannelId)
        try container.encodeIfPresent(channelName, forKey: .channelName)
        try container.encodeIfPresent(channelPrimaryImageTag, forKey: .channelPrimaryImageTag)
        try container.encodeIfPresent(programId, forKey: .programId)
        try container.encodeIfPresent(externalProgramId, forKey: .externalProgramId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(overview, forKey: .overview)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(prePaddingSeconds, forKey: .prePaddingSeconds)
        try container.encodeIfPresent(postPaddingSeconds, forKey: .postPaddingSeconds)
        try container.encodeIfPresent(isPrePaddingRequired, forKey: .isPrePaddingRequired)
        try container.encodeIfPresent(parentBackdropItemId, forKey: .parentBackdropItemId)
        try container.encodeIfPresent(parentBackdropImageTags, forKey: .parentBackdropImageTags)
        try container.encodeIfPresent(isPostPaddingRequired, forKey: .isPostPaddingRequired)
        try container.encodeIfPresent(keepUntil, forKey: .keepUntil)
    }
}

