//
// LiveTvLiveTvInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveTvLiveTvInfo: Codable, JSONEncodable, Hashable {

    public var services: [LiveTvLiveTvServiceInfo]?
    public var isEnabled: Bool?
    public var enabledUsers: [String]?

    public init(services: [LiveTvLiveTvServiceInfo]? = nil, isEnabled: Bool? = nil, enabledUsers: [String]? = nil) {
        self.services = services
        self.isEnabled = isEnabled
        self.enabledUsers = enabledUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case services = "Services"
        case isEnabled = "IsEnabled"
        case enabledUsers = "EnabledUsers"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(services, forKey: .services)
        try container.encodeIfPresent(isEnabled, forKey: .isEnabled)
        try container.encodeIfPresent(enabledUsers, forKey: .enabledUsers)
    }
}

