//
// LiveTvGetPrograms.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveTvGetPrograms: Codable, JSONEncodable, Hashable {

    public var isAiring: Bool?
    public var enableTotalRecordCount: Bool?
    public var seriesTimerId: String?
    public var librarySeriesId: String?

    public init(isAiring: Bool? = nil, enableTotalRecordCount: Bool? = nil, seriesTimerId: String? = nil, librarySeriesId: String? = nil) {
        self.isAiring = isAiring
        self.enableTotalRecordCount = enableTotalRecordCount
        self.seriesTimerId = seriesTimerId
        self.librarySeriesId = librarySeriesId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isAiring = "IsAiring"
        case enableTotalRecordCount = "EnableTotalRecordCount"
        case seriesTimerId = "SeriesTimerId"
        case librarySeriesId = "LibrarySeriesId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isAiring, forKey: .isAiring)
        try container.encodeIfPresent(enableTotalRecordCount, forKey: .enableTotalRecordCount)
        try container.encodeIfPresent(seriesTimerId, forKey: .seriesTimerId)
        try container.encodeIfPresent(librarySeriesId, forKey: .librarySeriesId)
    }
}

