//
// LogFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LogFile: Codable, JSONEncodable, Hashable {

    public var dateCreated: Date?
    public var dateModified: Date?
    public var size: Int64?
    public var name: String?

    public init(dateCreated: Date? = nil, dateModified: Date? = nil, size: Int64? = nil, name: String? = nil) {
        self.dateCreated = dateCreated
        self.dateModified = dateModified
        self.size = size
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dateCreated = "DateCreated"
        case dateModified = "DateModified"
        case size = "Size"
        case name = "Name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dateCreated, forKey: .dateCreated)
        try container.encodeIfPresent(dateModified, forKey: .dateModified)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

