//
// MediaInfoPlaybackInfoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaInfoPlaybackInfoRequest: Codable, JSONEncodable, Hashable {

    public enum DirectPlayProtocols: String, Codable, CaseIterable {
        case file = "File"
        case http = "Http"
        case rtmp = "Rtmp"
        case rtsp = "Rtsp"
        case udp = "Udp"
        case rtp = "Rtp"
        case ftp = "Ftp"
        case mms = "Mms"
    }
    public var id: String?
    public var userId: String?
    public var maxStreamingBitrate: Int64?
    public var startTimeTicks: Int64?
    public var audioStreamIndex: Int?
    public var subtitleStreamIndex: Int?
    public var maxAudioChannels: Int?
    public var mediaSourceId: String?
    public var liveStreamId: String?
    public var deviceProfile: DlnaDeviceProfile?
    public var enableDirectPlay: Bool?
    public var enableDirectStream: Bool?
    public var enableTranscoding: Bool?
    public var allowVideoStreamCopy: Bool?
    public var allowAudioStreamCopy: Bool?
    public var isPlayback: Bool?
    public var autoOpenLiveStream: Bool?
    public var directPlayProtocols: [DirectPlayProtocols]?

    public init(id: String? = nil, userId: String? = nil, maxStreamingBitrate: Int64? = nil, startTimeTicks: Int64? = nil, audioStreamIndex: Int? = nil, subtitleStreamIndex: Int? = nil, maxAudioChannels: Int? = nil, mediaSourceId: String? = nil, liveStreamId: String? = nil, deviceProfile: DlnaDeviceProfile? = nil, enableDirectPlay: Bool? = nil, enableDirectStream: Bool? = nil, enableTranscoding: Bool? = nil, allowVideoStreamCopy: Bool? = nil, allowAudioStreamCopy: Bool? = nil, isPlayback: Bool? = nil, autoOpenLiveStream: Bool? = nil, directPlayProtocols: [DirectPlayProtocols]? = nil) {
        self.id = id
        self.userId = userId
        self.maxStreamingBitrate = maxStreamingBitrate
        self.startTimeTicks = startTimeTicks
        self.audioStreamIndex = audioStreamIndex
        self.subtitleStreamIndex = subtitleStreamIndex
        self.maxAudioChannels = maxAudioChannels
        self.mediaSourceId = mediaSourceId
        self.liveStreamId = liveStreamId
        self.deviceProfile = deviceProfile
        self.enableDirectPlay = enableDirectPlay
        self.enableDirectStream = enableDirectStream
        self.enableTranscoding = enableTranscoding
        self.allowVideoStreamCopy = allowVideoStreamCopy
        self.allowAudioStreamCopy = allowAudioStreamCopy
        self.isPlayback = isPlayback
        self.autoOpenLiveStream = autoOpenLiveStream
        self.directPlayProtocols = directPlayProtocols
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case userId = "UserId"
        case maxStreamingBitrate = "MaxStreamingBitrate"
        case startTimeTicks = "StartTimeTicks"
        case audioStreamIndex = "AudioStreamIndex"
        case subtitleStreamIndex = "SubtitleStreamIndex"
        case maxAudioChannels = "MaxAudioChannels"
        case mediaSourceId = "MediaSourceId"
        case liveStreamId = "LiveStreamId"
        case deviceProfile = "DeviceProfile"
        case enableDirectPlay = "EnableDirectPlay"
        case enableDirectStream = "EnableDirectStream"
        case enableTranscoding = "EnableTranscoding"
        case allowVideoStreamCopy = "AllowVideoStreamCopy"
        case allowAudioStreamCopy = "AllowAudioStreamCopy"
        case isPlayback = "IsPlayback"
        case autoOpenLiveStream = "AutoOpenLiveStream"
        case directPlayProtocols = "DirectPlayProtocols"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(maxStreamingBitrate, forKey: .maxStreamingBitrate)
        try container.encodeIfPresent(startTimeTicks, forKey: .startTimeTicks)
        try container.encodeIfPresent(audioStreamIndex, forKey: .audioStreamIndex)
        try container.encodeIfPresent(subtitleStreamIndex, forKey: .subtitleStreamIndex)
        try container.encodeIfPresent(maxAudioChannels, forKey: .maxAudioChannels)
        try container.encodeIfPresent(mediaSourceId, forKey: .mediaSourceId)
        try container.encodeIfPresent(liveStreamId, forKey: .liveStreamId)
        try container.encodeIfPresent(deviceProfile, forKey: .deviceProfile)
        try container.encodeIfPresent(enableDirectPlay, forKey: .enableDirectPlay)
        try container.encodeIfPresent(enableDirectStream, forKey: .enableDirectStream)
        try container.encodeIfPresent(enableTranscoding, forKey: .enableTranscoding)
        try container.encodeIfPresent(allowVideoStreamCopy, forKey: .allowVideoStreamCopy)
        try container.encodeIfPresent(allowAudioStreamCopy, forKey: .allowAudioStreamCopy)
        try container.encodeIfPresent(isPlayback, forKey: .isPlayback)
        try container.encodeIfPresent(autoOpenLiveStream, forKey: .autoOpenLiveStream)
        try container.encodeIfPresent(directPlayProtocols, forKey: .directPlayProtocols)
    }
}

