//
// MediaEncodingCodecsCommonTypesProfileInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaEncodingCodecsCommonTypesProfileInformation: Codable, JSONEncodable, Hashable {

    public var shortName: String?
    public var description: String?
    public var details: String?
    public var id: String?

    public init(shortName: String? = nil, description: String? = nil, details: String? = nil, id: String? = nil) {
        self.shortName = shortName
        self.description = description
        self.details = details
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shortName = "ShortName"
        case description = "Description"
        case details = "Details"
        case id = "Id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(shortName, forKey: .shortName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

