//
// MediaEncodingCodecsCommonTypesProfileLevelInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MediaEncodingCodecsCommonTypesProfileLevelInformation: Codable, JSONEncodable, Hashable {

    public var profile: MediaEncodingCodecsCommonTypesProfileInformation?
    public var level: MediaEncodingCodecsCommonTypesLevelInformation?

    public init(profile: MediaEncodingCodecsCommonTypesProfileInformation? = nil, level: MediaEncodingCodecsCommonTypesLevelInformation? = nil) {
        self.profile = profile
        self.level = level
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile = "Profile"
        case level = "Level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(level, forKey: .level)
    }
}

