//
// QueryResultUserLibraryTagItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryResultUserLibraryTagItem: Codable, JSONEncodable, Hashable {

    public var items: [UserLibraryTagItem]?
    public var totalRecordCount: Int?

    public init(items: [UserLibraryTagItem]? = nil, totalRecordCount: Int? = nil) {
        self.items = items
        self.totalRecordCount = totalRecordCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items = "Items"
        case totalRecordCount = "TotalRecordCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(totalRecordCount, forKey: .totalRecordCount)
    }
}

