//
// QueueItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueueItem: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var playlistItemId: String?

    public init(id: Int64? = nil, playlistItemId: String? = nil) {
        self.id = id
        self.playlistItemId = playlistItemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case playlistItemId = "PlaylistItemId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(playlistItemId, forKey: .playlistItemId)
    }
}

