//
// RemoteImageInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RemoteImageInfo: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case primary = "Primary"
        case art = "Art"
        case backdrop = "Backdrop"
        case banner = "Banner"
        case logo = "Logo"
        case thumb = "Thumb"
        case disc = "Disc"
        case box = "Box"
        case screenshot = "Screenshot"
        case menu = "Menu"
        case chapter = "Chapter"
        case boxRear = "BoxRear"
        case thumbnail = "Thumbnail"
    }
    public enum RatingType: String, Codable, CaseIterable {
        case score = "Score"
        case likes = "Likes"
    }
    public var providerName: String?
    public var url: String?
    public var thumbnailUrl: String?
    public var height: Int?
    public var width: Int?
    public var communityRating: Double?
    public var voteCount: Int?
    public var language: String?
    public var type: ModelType?
    public var ratingType: RatingType?

    public init(providerName: String? = nil, url: String? = nil, thumbnailUrl: String? = nil, height: Int? = nil, width: Int? = nil, communityRating: Double? = nil, voteCount: Int? = nil, language: String? = nil, type: ModelType? = nil, ratingType: RatingType? = nil) {
        self.providerName = providerName
        self.url = url
        self.thumbnailUrl = thumbnailUrl
        self.height = height
        self.width = width
        self.communityRating = communityRating
        self.voteCount = voteCount
        self.language = language
        self.type = type
        self.ratingType = ratingType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerName = "ProviderName"
        case url = "Url"
        case thumbnailUrl = "ThumbnailUrl"
        case height = "Height"
        case width = "Width"
        case communityRating = "CommunityRating"
        case voteCount = "VoteCount"
        case language = "Language"
        case type = "Type"
        case ratingType = "RatingType"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providerName, forKey: .providerName)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(thumbnailUrl, forKey: .thumbnailUrl)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(communityRating, forKey: .communityRating)
        try container.encodeIfPresent(voteCount, forKey: .voteCount)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(ratingType, forKey: .ratingType)
    }
}

