//
// RokuMetadataApiThumbnailSetInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RokuMetadataApiThumbnailSetInfo: Codable, JSONEncodable, Hashable {

    public var aspectRatio: Double?
    public var thumbnails: [RokuMetadataApiThumbnailInfo]?

    public init(aspectRatio: Double? = nil, thumbnails: [RokuMetadataApiThumbnailInfo]? = nil) {
        self.aspectRatio = aspectRatio
        self.thumbnails = thumbnails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aspectRatio = "AspectRatio"
        case thumbnails = "Thumbnails"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encodeIfPresent(thumbnails, forKey: .thumbnails)
    }
}

