//
// SearchSearchHintResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchSearchHintResult: Codable, JSONEncodable, Hashable {

    public var searchHints: [SearchSearchHint]?
    public var totalRecordCount: Int?

    public init(searchHints: [SearchSearchHint]? = nil, totalRecordCount: Int? = nil) {
        self.searchHints = searchHints
        self.totalRecordCount = totalRecordCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchHints = "SearchHints"
        case totalRecordCount = "TotalRecordCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(searchHints, forKey: .searchHints)
        try container.encodeIfPresent(totalRecordCount, forKey: .totalRecordCount)
    }
}

