//
// SyncModelSyncDataRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncModelSyncDataRequest: Codable, JSONEncodable, Hashable {

    public var localItemIds: [String]?
    public var targetId: String?

    public init(localItemIds: [String]? = nil, targetId: String? = nil) {
        self.localItemIds = localItemIds
        self.targetId = targetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case localItemIds = "LocalItemIds"
        case targetId = "TargetId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(localItemIds, forKey: .localItemIds)
        try container.encodeIfPresent(targetId, forKey: .targetId)
    }
}

