//
// TasksTaskInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TasksTaskInfo: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case idle = "Idle"
        case cancelling = "Cancelling"
        case running = "Running"
    }
    public var name: String?
    public var state: State?
    public var currentProgressPercentage: Double?
    public var id: String?
    public var lastExecutionResult: TasksTaskResult?
    public var triggers: [TasksTaskTriggerInfo]?
    public var description: String?
    public var category: String?
    public var isHidden: Bool?
    public var key: String?

    public init(name: String? = nil, state: State? = nil, currentProgressPercentage: Double? = nil, id: String? = nil, lastExecutionResult: TasksTaskResult? = nil, triggers: [TasksTaskTriggerInfo]? = nil, description: String? = nil, category: String? = nil, isHidden: Bool? = nil, key: String? = nil) {
        self.name = name
        self.state = state
        self.currentProgressPercentage = currentProgressPercentage
        self.id = id
        self.lastExecutionResult = lastExecutionResult
        self.triggers = triggers
        self.description = description
        self.category = category
        self.isHidden = isHidden
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case state = "State"
        case currentProgressPercentage = "CurrentProgressPercentage"
        case id = "Id"
        case lastExecutionResult = "LastExecutionResult"
        case triggers = "Triggers"
        case description = "Description"
        case category = "Category"
        case isHidden = "IsHidden"
        case key = "Key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(currentProgressPercentage, forKey: .currentProgressPercentage)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(lastExecutionResult, forKey: .lastExecutionResult)
        try container.encodeIfPresent(triggers, forKey: .triggers)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(isHidden, forKey: .isHidden)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

