//
// ThemeMediaResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ThemeMediaResult: Codable, JSONEncodable, Hashable {

    public var ownerId: Int64?
    public var items: [BaseItemDto]?
    public var totalRecordCount: Int?

    public init(ownerId: Int64? = nil, items: [BaseItemDto]? = nil, totalRecordCount: Int? = nil) {
        self.ownerId = ownerId
        self.items = items
        self.totalRecordCount = totalRecordCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ownerId = "OwnerId"
        case items = "Items"
        case totalRecordCount = "TotalRecordCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(totalRecordCount, forKey: .totalRecordCount)
    }
}

