//
// TupleDoubleDouble.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TupleDoubleDouble: Codable, JSONEncodable, Hashable {

    public var item1: Double?
    public var item2: Double?

    public init(item1: Double? = nil, item2: Double? = nil) {
        self.item1 = item1
        self.item2 = item2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item1 = "Item1"
        case item2 = "Item2"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(item1, forKey: .item1)
        try container.encodeIfPresent(item2, forKey: .item2)
    }
}

