//
// UpdateUserEasyPassword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserEasyPassword: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var newPw: String?
    public var resetPassword: Bool?

    public init(id: String? = nil, newPw: String? = nil, resetPassword: Bool? = nil) {
        self.id = id
        self.newPw = newPw
        self.resetPassword = resetPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case newPw = "NewPw"
        case resetPassword = "ResetPassword"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(newPw, forKey: .newPw)
        try container.encodeIfPresent(resetPassword, forKey: .resetPassword)
    }
}

