//
// UsersUserPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersUserPolicy: Codable, JSONEncodable, Hashable {

    public enum BlockUnratedItems: String, Codable, CaseIterable {
        case movie = "Movie"
        case trailer = "Trailer"
        case series = "Series"
        case music = "Music"
        case game = "Game"
        case book = "Book"
        case liveTvChannel = "LiveTvChannel"
        case liveTvProgram = "LiveTvProgram"
        case channelContent = "ChannelContent"
        case other = "Other"
    }
    public var isAdministrator: Bool?
    public var isHidden: Bool?
    public var isHiddenRemotely: Bool?
    public var isDisabled: Bool?
    public var maxParentalRating: Int?
    public var blockedTags: [String]?
    public var enableUserPreferenceAccess: Bool?
    public var accessSchedules: [ConfigurationAccessSchedule]?
    public var blockUnratedItems: [BlockUnratedItems]?
    public var enableRemoteControlOfOtherUsers: Bool?
    public var enableSharedDeviceControl: Bool?
    public var enableRemoteAccess: Bool?
    public var enableLiveTvManagement: Bool?
    public var enableLiveTvAccess: Bool?
    public var enableMediaPlayback: Bool?
    public var enableAudioPlaybackTranscoding: Bool?
    public var enableVideoPlaybackTranscoding: Bool?
    public var enablePlaybackRemuxing: Bool?
    public var enableContentDeletion: Bool?
    public var enableContentDeletionFromFolders: [String]?
    public var enableContentDownloading: Bool?
    public var enableSubtitleDownloading: Bool?
    public var enableSubtitleManagement: Bool?
    public var enableSyncTranscoding: Bool?
    public var enableMediaConversion: Bool?
    public var enabledDevices: [String]?
    public var enableAllDevices: Bool?
    public var enabledChannels: [String]?
    public var enableAllChannels: Bool?
    public var enabledFolders: [String]?
    public var enableAllFolders: Bool?
    public var invalidLoginAttemptCount: Int?
    public var enablePublicSharing: Bool?
    public var blockedMediaFolders: [String]?
    public var blockedChannels: [String]?
    public var remoteClientBitrateLimit: Int?
    public var authenticationProviderId: String?
    public var excludedSubFolders: [String]?
    public var disablePremiumFeatures: Bool?

    public init(isAdministrator: Bool? = nil, isHidden: Bool? = nil, isHiddenRemotely: Bool? = nil, isDisabled: Bool? = nil, maxParentalRating: Int? = nil, blockedTags: [String]? = nil, enableUserPreferenceAccess: Bool? = nil, accessSchedules: [ConfigurationAccessSchedule]? = nil, blockUnratedItems: [BlockUnratedItems]? = nil, enableRemoteControlOfOtherUsers: Bool? = nil, enableSharedDeviceControl: Bool? = nil, enableRemoteAccess: Bool? = nil, enableLiveTvManagement: Bool? = nil, enableLiveTvAccess: Bool? = nil, enableMediaPlayback: Bool? = nil, enableAudioPlaybackTranscoding: Bool? = nil, enableVideoPlaybackTranscoding: Bool? = nil, enablePlaybackRemuxing: Bool? = nil, enableContentDeletion: Bool? = nil, enableContentDeletionFromFolders: [String]? = nil, enableContentDownloading: Bool? = nil, enableSubtitleDownloading: Bool? = nil, enableSubtitleManagement: Bool? = nil, enableSyncTranscoding: Bool? = nil, enableMediaConversion: Bool? = nil, enabledDevices: [String]? = nil, enableAllDevices: Bool? = nil, enabledChannels: [String]? = nil, enableAllChannels: Bool? = nil, enabledFolders: [String]? = nil, enableAllFolders: Bool? = nil, invalidLoginAttemptCount: Int? = nil, enablePublicSharing: Bool? = nil, blockedMediaFolders: [String]? = nil, blockedChannels: [String]? = nil, remoteClientBitrateLimit: Int? = nil, authenticationProviderId: String? = nil, excludedSubFolders: [String]? = nil, disablePremiumFeatures: Bool? = nil) {
        self.isAdministrator = isAdministrator
        self.isHidden = isHidden
        self.isHiddenRemotely = isHiddenRemotely
        self.isDisabled = isDisabled
        self.maxParentalRating = maxParentalRating
        self.blockedTags = blockedTags
        self.enableUserPreferenceAccess = enableUserPreferenceAccess
        self.accessSchedules = accessSchedules
        self.blockUnratedItems = blockUnratedItems
        self.enableRemoteControlOfOtherUsers = enableRemoteControlOfOtherUsers
        self.enableSharedDeviceControl = enableSharedDeviceControl
        self.enableRemoteAccess = enableRemoteAccess
        self.enableLiveTvManagement = enableLiveTvManagement
        self.enableLiveTvAccess = enableLiveTvAccess
        self.enableMediaPlayback = enableMediaPlayback
        self.enableAudioPlaybackTranscoding = enableAudioPlaybackTranscoding
        self.enableVideoPlaybackTranscoding = enableVideoPlaybackTranscoding
        self.enablePlaybackRemuxing = enablePlaybackRemuxing
        self.enableContentDeletion = enableContentDeletion
        self.enableContentDeletionFromFolders = enableContentDeletionFromFolders
        self.enableContentDownloading = enableContentDownloading
        self.enableSubtitleDownloading = enableSubtitleDownloading
        self.enableSubtitleManagement = enableSubtitleManagement
        self.enableSyncTranscoding = enableSyncTranscoding
        self.enableMediaConversion = enableMediaConversion
        self.enabledDevices = enabledDevices
        self.enableAllDevices = enableAllDevices
        self.enabledChannels = enabledChannels
        self.enableAllChannels = enableAllChannels
        self.enabledFolders = enabledFolders
        self.enableAllFolders = enableAllFolders
        self.invalidLoginAttemptCount = invalidLoginAttemptCount
        self.enablePublicSharing = enablePublicSharing
        self.blockedMediaFolders = blockedMediaFolders
        self.blockedChannels = blockedChannels
        self.remoteClientBitrateLimit = remoteClientBitrateLimit
        self.authenticationProviderId = authenticationProviderId
        self.excludedSubFolders = excludedSubFolders
        self.disablePremiumFeatures = disablePremiumFeatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isAdministrator = "IsAdministrator"
        case isHidden = "IsHidden"
        case isHiddenRemotely = "IsHiddenRemotely"
        case isDisabled = "IsDisabled"
        case maxParentalRating = "MaxParentalRating"
        case blockedTags = "BlockedTags"
        case enableUserPreferenceAccess = "EnableUserPreferenceAccess"
        case accessSchedules = "AccessSchedules"
        case blockUnratedItems = "BlockUnratedItems"
        case enableRemoteControlOfOtherUsers = "EnableRemoteControlOfOtherUsers"
        case enableSharedDeviceControl = "EnableSharedDeviceControl"
        case enableRemoteAccess = "EnableRemoteAccess"
        case enableLiveTvManagement = "EnableLiveTvManagement"
        case enableLiveTvAccess = "EnableLiveTvAccess"
        case enableMediaPlayback = "EnableMediaPlayback"
        case enableAudioPlaybackTranscoding = "EnableAudioPlaybackTranscoding"
        case enableVideoPlaybackTranscoding = "EnableVideoPlaybackTranscoding"
        case enablePlaybackRemuxing = "EnablePlaybackRemuxing"
        case enableContentDeletion = "EnableContentDeletion"
        case enableContentDeletionFromFolders = "EnableContentDeletionFromFolders"
        case enableContentDownloading = "EnableContentDownloading"
        case enableSubtitleDownloading = "EnableSubtitleDownloading"
        case enableSubtitleManagement = "EnableSubtitleManagement"
        case enableSyncTranscoding = "EnableSyncTranscoding"
        case enableMediaConversion = "EnableMediaConversion"
        case enabledDevices = "EnabledDevices"
        case enableAllDevices = "EnableAllDevices"
        case enabledChannels = "EnabledChannels"
        case enableAllChannels = "EnableAllChannels"
        case enabledFolders = "EnabledFolders"
        case enableAllFolders = "EnableAllFolders"
        case invalidLoginAttemptCount = "InvalidLoginAttemptCount"
        case enablePublicSharing = "EnablePublicSharing"
        case blockedMediaFolders = "BlockedMediaFolders"
        case blockedChannels = "BlockedChannels"
        case remoteClientBitrateLimit = "RemoteClientBitrateLimit"
        case authenticationProviderId = "AuthenticationProviderId"
        case excludedSubFolders = "ExcludedSubFolders"
        case disablePremiumFeatures = "DisablePremiumFeatures"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isAdministrator, forKey: .isAdministrator)
        try container.encodeIfPresent(isHidden, forKey: .isHidden)
        try container.encodeIfPresent(isHiddenRemotely, forKey: .isHiddenRemotely)
        try container.encodeIfPresent(isDisabled, forKey: .isDisabled)
        try container.encodeIfPresent(maxParentalRating, forKey: .maxParentalRating)
        try container.encodeIfPresent(blockedTags, forKey: .blockedTags)
        try container.encodeIfPresent(enableUserPreferenceAccess, forKey: .enableUserPreferenceAccess)
        try container.encodeIfPresent(accessSchedules, forKey: .accessSchedules)
        try container.encodeIfPresent(blockUnratedItems, forKey: .blockUnratedItems)
        try container.encodeIfPresent(enableRemoteControlOfOtherUsers, forKey: .enableRemoteControlOfOtherUsers)
        try container.encodeIfPresent(enableSharedDeviceControl, forKey: .enableSharedDeviceControl)
        try container.encodeIfPresent(enableRemoteAccess, forKey: .enableRemoteAccess)
        try container.encodeIfPresent(enableLiveTvManagement, forKey: .enableLiveTvManagement)
        try container.encodeIfPresent(enableLiveTvAccess, forKey: .enableLiveTvAccess)
        try container.encodeIfPresent(enableMediaPlayback, forKey: .enableMediaPlayback)
        try container.encodeIfPresent(enableAudioPlaybackTranscoding, forKey: .enableAudioPlaybackTranscoding)
        try container.encodeIfPresent(enableVideoPlaybackTranscoding, forKey: .enableVideoPlaybackTranscoding)
        try container.encodeIfPresent(enablePlaybackRemuxing, forKey: .enablePlaybackRemuxing)
        try container.encodeIfPresent(enableContentDeletion, forKey: .enableContentDeletion)
        try container.encodeIfPresent(enableContentDeletionFromFolders, forKey: .enableContentDeletionFromFolders)
        try container.encodeIfPresent(enableContentDownloading, forKey: .enableContentDownloading)
        try container.encodeIfPresent(enableSubtitleDownloading, forKey: .enableSubtitleDownloading)
        try container.encodeIfPresent(enableSubtitleManagement, forKey: .enableSubtitleManagement)
        try container.encodeIfPresent(enableSyncTranscoding, forKey: .enableSyncTranscoding)
        try container.encodeIfPresent(enableMediaConversion, forKey: .enableMediaConversion)
        try container.encodeIfPresent(enabledDevices, forKey: .enabledDevices)
        try container.encodeIfPresent(enableAllDevices, forKey: .enableAllDevices)
        try container.encodeIfPresent(enabledChannels, forKey: .enabledChannels)
        try container.encodeIfPresent(enableAllChannels, forKey: .enableAllChannels)
        try container.encodeIfPresent(enabledFolders, forKey: .enabledFolders)
        try container.encodeIfPresent(enableAllFolders, forKey: .enableAllFolders)
        try container.encodeIfPresent(invalidLoginAttemptCount, forKey: .invalidLoginAttemptCount)
        try container.encodeIfPresent(enablePublicSharing, forKey: .enablePublicSharing)
        try container.encodeIfPresent(blockedMediaFolders, forKey: .blockedMediaFolders)
        try container.encodeIfPresent(blockedChannels, forKey: .blockedChannels)
        try container.encodeIfPresent(remoteClientBitrateLimit, forKey: .remoteClientBitrateLimit)
        try container.encodeIfPresent(authenticationProviderId, forKey: .authenticationProviderId)
        try container.encodeIfPresent(excludedSubFolders, forKey: .excludedSubFolders)
        try container.encodeIfPresent(disablePremiumFeatures, forKey: .disablePremiumFeatures)
    }
}

