//
// UsersPinRedeemResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersPinRedeemResult: Codable, JSONEncodable, Hashable {

    public var success: Bool?
    public var usersReset: [String]?

    public init(success: Bool? = nil, usersReset: [String]? = nil) {
        self.success = success
        self.usersReset = usersReset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success = "Success"
        case usersReset = "UsersReset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(usersReset, forKey: .usersReset)
    }
}

